-- H2 schema for the unitemporal pet-store Reladomo model.
-- BUSINESS tables carry FROM_Z / THRU_Z (GenericNonAuditedTemporalDirector).
-- AUDIT tables carry IN_Z / OUT_Z (AuditOnlyTemporalDirector).
-- PLAIN tables have no temporal columns.
-- Physical unique key is logical PK plus the temporal FROM/IN column.

DROP TABLE IF EXISTS FEEDING_SCHEDULE;
DROP TABLE IF EXISTS VETERINARY_VISIT;
DROP TABLE IF EXISTS VACCINATION;
DROP TABLE IF EXISTS GROOMING_APPOINTMENT;
DROP TABLE IF EXISTS SALES_ORDER_LINE;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS PURCHASE_ORDER_LINE;
DROP TABLE IF EXISTS SHIPMENT;
DROP TABLE IF EXISTS ADOPTION;
DROP TABLE IF EXISTS SALES_ORDER;
DROP TABLE IF EXISTS PURCHASE_ORDER;
DROP TABLE IF EXISTS STOCK_LEVEL;
DROP TABLE IF EXISTS PET;
DROP TABLE IF EXISTS BREED;
DROP TABLE IF EXISTS KENNEL;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SPECIES;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS PET_OWNER;
DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS SUPPLIER;

CREATE TABLE SPECIES (
    SPECIES_ID BIGINT NOT NULL,
    COMMON_NAME VARCHAR(80) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(120) NOT NULL,
    CARE_LEVEL VARCHAR(32) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX SPECIES_PK ON SPECIES (SPECIES_ID, FROM_Z);

CREATE TABLE BREED (
    BREED_ID BIGINT NOT NULL,
    SPECIES_ID BIGINT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    SIZE_CATEGORY VARCHAR(32) NOT NULL,
    TYPICAL_LIFESPAN_YEARS INTEGER NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX BREED_PK ON BREED (BREED_ID, FROM_Z);

CREATE TABLE STORE (
    STORE_ID BIGINT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    ADDRESS_LINE1 VARCHAR(120) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    POSTAL_CODE VARCHAR(16) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    OPENED_DATE TIMESTAMP NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX STORE_PK ON STORE (STORE_ID, FROM_Z);

CREATE TABLE KENNEL (
    KENNEL_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    LABEL VARCHAR(64) NOT NULL,
    CAPACITY INTEGER NOT NULL,
    ZONE VARCHAR(32) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX KENNEL_PK ON KENNEL (KENNEL_ID, FROM_Z);

CREATE TABLE PRODUCT_CATEGORY (
    CATEGORY_ID BIGINT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    PARENT_CATEGORY_ID BIGINT
);
CREATE UNIQUE INDEX PRODUCT_CATEGORY_PK ON PRODUCT_CATEGORY (CATEGORY_ID);

CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT NOT NULL,
    SKU VARCHAR(32) NOT NULL,
    NAME VARCHAR(120) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT (PRODUCT_ID, FROM_Z);

CREATE TABLE PET (
    PET_ID BIGINT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    SPECIES_ID BIGINT NOT NULL,
    BREED_ID BIGINT,
    DATE_OF_BIRTH TIMESTAMP NOT NULL,
    SEX VARCHAR(16) NOT NULL,
    COLOR_CODE VARCHAR(32) NOT NULL,
    MICROCHIP_ID VARCHAR(64),
    STATUS VARCHAR(32) NOT NULL,
    KENNEL_ID BIGINT,
    LIST_PRICE DECIMAL(18, 2) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PET_PK ON PET (PET_ID, FROM_Z);

CREATE TABLE FEEDING_SCHEDULE (
    SCHEDULE_ID BIGINT NOT NULL,
    PET_ID BIGINT NOT NULL,
    FEED_TIME_OF_DAY VARCHAR(16) NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY_GRAMS INTEGER NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX FEEDING_SCHEDULE_PK ON FEEDING_SCHEDULE (SCHEDULE_ID, FROM_Z);

CREATE TABLE VETERINARY_VISIT (
    VISIT_ID BIGINT NOT NULL,
    PET_ID BIGINT NOT NULL,
    VET_ID BIGINT NOT NULL,
    VISIT_TIME TIMESTAMP NOT NULL,
    REASON VARCHAR(120) NOT NULL,
    DIAGNOSIS VARCHAR(255) NOT NULL,
    FOLLOW_UP_DATE TIMESTAMP,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX VETERINARY_VISIT_PK ON VETERINARY_VISIT (VISIT_ID, IN_Z);

CREATE TABLE VACCINATION (
    VACCINATION_ID BIGINT NOT NULL,
    PET_ID BIGINT NOT NULL,
    VACCINE_CODE VARCHAR(32) NOT NULL,
    ADMINISTERED_TIME TIMESTAMP NOT NULL,
    BATCH_NUMBER VARCHAR(64) NOT NULL,
    NEXT_DUE_DATE TIMESTAMP NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX VACCINATION_PK ON VACCINATION (VACCINATION_ID, IN_Z);

CREATE TABLE GROOMING_APPOINTMENT (
    APPOINTMENT_ID BIGINT NOT NULL,
    PET_ID BIGINT NOT NULL,
    GROOMER_ID BIGINT NOT NULL,
    SCHEDULED_TIME TIMESTAMP NOT NULL,
    SERVICE_CODE VARCHAR(32) NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX GROOMING_APPOINTMENT_PK ON GROOMING_APPOINTMENT (APPOINTMENT_ID, IN_Z);

CREATE TABLE STOCK_LEVEL (
    STOCK_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY_ON_HAND INTEGER NOT NULL,
    REORDER_POINT INTEGER NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX STOCK_LEVEL_PK ON STOCK_LEVEL (STOCK_ID, FROM_Z);

CREATE TABLE PET_OWNER (
    OWNER_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    ADDRESS_LINE1 VARCHAR(120) NOT NULL,
    CITY VARCHAR(64) NOT NULL,
    POSTAL_CODE VARCHAR(16) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PET_OWNER_PK ON PET_OWNER (OWNER_ID, FROM_Z);

CREATE TABLE SALES_ORDER (
    ORDER_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    ORDER_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    TOTAL_AMOUNT DECIMAL(18, 2) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX SALES_ORDER_PK ON SALES_ORDER (ORDER_ID, IN_Z);

CREATE TABLE SALES_ORDER_LINE (
    LINE_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT,
    PET_ID BIGINT,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(18, 2) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX SALES_ORDER_LINE_PK ON SALES_ORDER_LINE (LINE_ID, IN_Z);

CREATE TABLE PAYMENT (
    PAYMENT_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    AMOUNT DECIMAL(18, 2) NOT NULL,
    PAID_TIME TIMESTAMP NOT NULL,
    METHOD VARCHAR(32) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PAYMENT_PK ON PAYMENT (PAYMENT_ID, IN_Z);

CREATE TABLE SUPPLIER (
    SUPPLIER_ID BIGINT NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    CONTACT_EMAIL VARCHAR(120) NOT NULL,
    LEAD_TIME_DAYS INTEGER NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX SUPPLIER_PK ON SUPPLIER (SUPPLIER_ID, FROM_Z);

CREATE TABLE PURCHASE_ORDER (
    PO_ID BIGINT NOT NULL,
    SUPPLIER_ID BIGINT NOT NULL,
    ORDERED_TIME TIMESTAMP NOT NULL,
    EXPECTED_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(32) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PURCHASE_ORDER_PK ON PURCHASE_ORDER (PO_ID, IN_Z);

CREATE TABLE PURCHASE_ORDER_LINE (
    PO_LINE_ID BIGINT NOT NULL,
    PO_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_COST DECIMAL(18, 2) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX PURCHASE_ORDER_LINE_PK ON PURCHASE_ORDER_LINE (PO_LINE_ID, IN_Z);

CREATE TABLE SHIPMENT (
    SHIPMENT_ID BIGINT NOT NULL,
    PO_ID BIGINT NOT NULL,
    SHIPPED_TIME TIMESTAMP NOT NULL,
    RECEIVED_TIME TIMESTAMP,
    CARRIER VARCHAR(64) NOT NULL,
    TRACKING_REF VARCHAR(64) NOT NULL,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX SHIPMENT_PK ON SHIPMENT (SHIPMENT_ID, IN_Z);

CREATE TABLE ADOPTION (
    ADOPTION_ID BIGINT NOT NULL,
    PET_ID BIGINT NOT NULL,
    OWNER_ID BIGINT NOT NULL,
    ADOPTED_TIME TIMESTAMP NOT NULL,
    FEE_AMOUNT DECIMAL(18, 2) NOT NULL,
    RETURNED_TIME TIMESTAMP,
    IN_Z TIMESTAMP NOT NULL,
    OUT_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ADOPTION_PK ON ADOPTION (ADOPTION_ID, IN_Z);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID BIGINT NOT NULL,
    STORE_ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    ROLE VARCHAR(32) NOT NULL,
    HIRE_DATE TIMESTAMP NOT NULL,
    HOURLY_RATE DECIMAL(18, 2) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL,
    THRU_Z TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX EMPLOYEE_PK ON EMPLOYEE (EMPLOYEE_ID, FROM_Z);
