DROP TABLE IF EXISTS SPIKE_BALANCE;
CREATE TABLE SPIKE_BALANCE (
    BALANCE_ID INTEGER      NOT NULL,
    ACCOUNT_ID INTEGER      NOT NULL,
    QUANTITY   DOUBLE       NOT NULL,
    LABEL      VARCHAR(64)  NULL,
    FROM_Z     TIMESTAMP    NOT NULL,
    THRU_Z     TIMESTAMP    NOT NULL,
    IN_Z       TIMESTAMP    NOT NULL,
    OUT_Z      TIMESTAMP    NOT NULL
);
CREATE INDEX SPIKE_BALANCE_PK ON SPIKE_BALANCE (BALANCE_ID, ACCOUNT_ID, FROM_Z, IN_Z);
