-- H2 schema for car-classifier-demo. Types match Reladomo H2DatabaseType 18.1.0.
-- BITEMPORAL tables carry FROM_Z/THRU_Z and IN_Z/OUT_Z.
-- AUDIT tables carry IN_Z/OUT_Z only.
-- PLAIN tables have no temporal columns.

DROP TABLE IF EXISTS CLASSIFICATION_RESULT;
DROP TABLE IF EXISTS RULE_CRITERION;
DROP TABLE IF EXISTS CLASSIFICATION_RULE;
DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS RESULT_LABEL;

CREATE TABLE RESULT_LABEL
(
    LABEL_CODE varchar(32) NOT NULL,
    DISPLAY_NAME varchar(64) NOT NULL,
    DESCRIPTION varchar(256) NOT NULL
);
CREATE UNIQUE INDEX RESULT_LABEL_PK ON RESULT_LABEL (LABEL_CODE);

CREATE TABLE CAR
(
    CAR_ID int NOT NULL,
    CAR_YEAR int NOT NULL,
    MAKE varchar(64) NOT NULL,
    MODEL varchar(64) NOT NULL,
    WHEEL_COUNT int NOT NULL,
    COLOR_CODE varchar(32) NOT NULL,
    BODY_STYLE varchar(32) NOT NULL,
    ENGINE_CODE varchar(32) NOT NULL
);
CREATE UNIQUE INDEX CAR_PK ON CAR (CAR_ID);

CREATE TABLE CLASSIFICATION_RULE
(
    RULE_ID int NOT NULL,
    RULE_NAME varchar(64) NOT NULL,
    PRIORITY int NOT NULL,
    RESULT_LABEL varchar(32) NOT NULL,
    IS_ACTIVE boolean NOT NULL,
    FROM_Z datetime NOT NULL,
    THRU_Z datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CLASSIFICATION_RULE_PK ON CLASSIFICATION_RULE (RULE_ID, FROM_Z, IN_Z);

CREATE TABLE RULE_CRITERION
(
    CRITERION_ID int NOT NULL,
    RULE_ID int NOT NULL,
    ATTRIBUTE_NAME varchar(32) NOT NULL,
    CRITERION_OPERATOR varchar(16) NOT NULL,
    VALUE_TEXT varchar(256),
    VALUE_NUMERIC_LOW int,
    VALUE_NUMERIC_HIGH int,
    FROM_Z datetime NOT NULL,
    THRU_Z datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX RULE_CRITERION_PK ON RULE_CRITERION (CRITERION_ID, FROM_Z, IN_Z);

CREATE TABLE CLASSIFICATION_RESULT
(
    RESULT_ID int NOT NULL,
    CAR_ID int NOT NULL,
    RULE_ID int NOT NULL,
    RESULT_LABEL varchar(32) NOT NULL,
    EVALUATED_AS_OF_DATE datetime NOT NULL,
    EVALUATED_TIME datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CLASSIFICATION_RESULT_PK ON CLASSIFICATION_RESULT (RESULT_ID, IN_Z);
