DROP TABLE IF EXISTS PLAN_RULE;
CREATE TABLE PLAN_RULE (
    RULE_ID       INTEGER      NOT NULL,
    RULE_NAME     VARCHAR(64)  NOT NULL,
    PRIORITY      INTEGER      NOT NULL,
    RESULT_LABEL  VARCHAR(32)  NOT NULL,
    IS_ACTIVE     BOOLEAN      NOT NULL,
    FROM_Z        TIMESTAMP    NOT NULL,
    THRU_Z        TIMESTAMP    NOT NULL,
    IN_Z          TIMESTAMP    NOT NULL,
    OUT_Z         TIMESTAMP    NOT NULL
);
CREATE INDEX PLAN_RULE_PK ON PLAN_RULE (RULE_ID, FROM_Z, IN_Z);

DROP TABLE IF EXISTS PLAN_CUSTOMER;
CREATE TABLE PLAN_CUSTOMER (
    ID      INTEGER       NOT NULL,
    EMAIL   VARCHAR(128)  NOT NULL,
    STATUS  VARCHAR(32)   NOT NULL
);
CREATE INDEX PLAN_CUSTOMER_PK ON PLAN_CUSTOMER (ID);

DROP TABLE IF EXISTS PLAN_POSITION;
CREATE TABLE PLAN_POSITION (
    ACCOUNT_ID  BIGINT        NOT NULL,
    PRODUCT_ID  INTEGER       NOT NULL,
    QUANTITY    DOUBLE        NOT NULL,
    STATUS      VARCHAR(32)   NOT NULL,
    FROM_Z      TIMESTAMP     NOT NULL,
    THRU_Z      TIMESTAMP     NOT NULL,
    IN_Z        TIMESTAMP     NOT NULL,
    OUT_Z       TIMESTAMP     NOT NULL
);
CREATE INDEX PLAN_POSITION_PK ON PLAN_POSITION (ACCOUNT_ID, PRODUCT_ID, FROM_Z, IN_Z);
