-- H2 schema for crm-bitemporal-demo. Types match Reladomo H2DatabaseType 18.1.0.

DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS PRICE_BOOK;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS LEAD_SOURCE;
DROP TABLE IF EXISTS PIPELINE_STAGE;
DROP TABLE IF EXISTS CUSTOMER_SEGMENT;
DROP TABLE IF EXISTS INDUSTRY;
DROP TABLE IF EXISTS TERRITORY;
DROP TABLE IF EXISTS TEAM;
DROP TABLE IF EXISTS SALES_REP;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS INVOICE_LINE;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS SLA_POLICY;
DROP TABLE IF EXISTS CASE_ESCALATION;
DROP TABLE IF EXISTS SUPPORT_CASE;
DROP TABLE IF EXISTS MESSAGE_TEMPLATE;
DROP TABLE IF EXISTS OUTREACH_ENROLLMENT;
DROP TABLE IF EXISTS OUTREACH_STEP;
DROP TABLE IF EXISTS OUTREACH_SEQUENCE;
DROP TABLE IF EXISTS CAMPAIGN_MEMBER;
DROP TABLE IF EXISTS CAMPAIGN;
DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS CASE_COMMENT;
DROP TABLE IF EXISTS NOTE_RECORD;
DROP TABLE IF EXISTS TASK_ITEM;
DROP TABLE IF EXISTS MEETING;
DROP TABLE IF EXISTS EMAIL_MESSAGE;
DROP TABLE IF EXISTS CALL_RECORD;
DROP TABLE IF EXISTS PRICE_BOOK_ENTRY;
DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS QUOTE_LINE_ITEM;
DROP TABLE IF EXISTS QUOTE;
DROP TABLE IF EXISTS OPPORTUNITY;
DROP TABLE IF EXISTS CONTACT_EMAIL;
DROP TABLE IF EXISTS CONTACT_PHONE;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CONSENT_RECORD;
DROP TABLE IF EXISTS CREDIT_RATING;
DROP TABLE IF EXISTS TERRITORY_ASSIGNMENT;
DROP TABLE IF EXISTS CUSTOMER_SEGMENT_ASSIGNMENT;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS CUSTOMER;

-- Customer (BITEMPORAL)
CREATE TABLE CUSTOMER
(
    CUSTOMER_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    LEGAL_NAME varchar(256) NOT NULL,
    INDUSTRY_ID varchar(32) NOT NULL,
    SEGMENT_CODE varchar(32) NOT NULL,
    STATUS varchar(32) NOT NULL,
    ANNUAL_REVENUE decimal(18,2) NOT NULL,
    EMPLOYEE_COUNT int NOT NULL,
    OWNER_REP_ID bigint NOT NULL,
    CREATED_DATE datetime NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CUSTOMER_PK ON CUSTOMER (CUSTOMER_ID, BUSINESS_DATE_FROM, IN_Z);

-- Account (BITEMPORAL)
CREATE TABLE ACCOUNT
(
    ACCOUNT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    ACCOUNT_NUMBER varchar(64) NOT NULL,
    ACCOUNT_TYPE varchar(32) NOT NULL,
    OPENED_DATE datetime NOT NULL,
    CLOSED_DATE datetime NULL,
    CREDIT_LIMIT decimal(18,2) NOT NULL,
    CURRENCY varchar(3) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX ACCOUNT_PK ON ACCOUNT (ACCOUNT_ID, BUSINESS_DATE_FROM, IN_Z);

-- Contact (BITEMPORAL)
CREATE TABLE CONTACT
(
    CONTACT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    FIRST_NAME varchar(64) NOT NULL,
    LAST_NAME varchar(64) NOT NULL,
    TITLE varchar(128) NOT NULL,
    DEPARTMENT varchar(64) NOT NULL,
    IS_PRIMARY boolean NOT NULL,
    PREFERRED_CHANNEL varchar(32) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CONTACT_PK ON CONTACT (CONTACT_ID, BUSINESS_DATE_FROM, IN_Z);

-- Company (BITEMPORAL)
CREATE TABLE COMPANY
(
    COMPANY_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    DUNS varchar(32) NOT NULL,
    PARENT_COMPANY_ID bigint NULL,
    COUNTRY_CODE varchar(2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX COMPANY_PK ON COMPANY (COMPANY_ID, BUSINESS_DATE_FROM, IN_Z);

-- CustomerSegmentAssignment (BITEMPORAL)
CREATE TABLE CUSTOMER_SEGMENT_ASSIGNMENT
(
    ASSIGNMENT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    SEGMENT_CODE varchar(32) NOT NULL,
    ASSIGNED_REASON varchar(256) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CUSTOMER_SEGMENT_ASSIGNMENT_PK ON CUSTOMER_SEGMENT_ASSIGNMENT (ASSIGNMENT_ID, BUSINESS_DATE_FROM, IN_Z);

-- TerritoryAssignment (BITEMPORAL)
CREATE TABLE TERRITORY_ASSIGNMENT
(
    ASSIGNMENT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    TERRITORY_ID bigint NOT NULL,
    REP_ID bigint NOT NULL,
    IS_PRIMARY boolean NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX TERRITORY_ASSIGNMENT_PK ON TERRITORY_ASSIGNMENT (ASSIGNMENT_ID, BUSINESS_DATE_FROM, IN_Z);

-- CreditRating (BITEMPORAL)
CREATE TABLE CREDIT_RATING
(
    RATING_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    RATING_CODE varchar(16) NOT NULL,
    SCORE_NUMERIC int NOT NULL,
    AGENCY varchar(64) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CREDIT_RATING_PK ON CREDIT_RATING (RATING_ID, BUSINESS_DATE_FROM, IN_Z);

-- ConsentRecord (BITEMPORAL)
CREATE TABLE CONSENT_RECORD
(
    CONSENT_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    CHANNEL varchar(32) NOT NULL,
    GRANTED boolean NOT NULL,
    LAWFUL_BASIS varchar(64) NOT NULL,
    SOURCE_REF varchar(128) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CONSENT_RECORD_PK ON CONSENT_RECORD (CONSENT_ID, BUSINESS_DATE_FROM, IN_Z);

-- Address (BITEMPORAL)
CREATE TABLE ADDRESS
(
    ADDRESS_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    ADDRESS_TYPE varchar(32) NOT NULL,
    LINE1 varchar(256) NOT NULL,
    LINE2 varchar(256) NULL,
    CITY varchar(64) NOT NULL,
    "STATE" varchar(64) NOT NULL,
    POSTAL_CODE varchar(16) NOT NULL,
    COUNTRY_CODE varchar(2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX ADDRESS_PK ON ADDRESS (ADDRESS_ID, BUSINESS_DATE_FROM, IN_Z);

-- ContactPhone (BITEMPORAL)
CREATE TABLE CONTACT_PHONE
(
    PHONE_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    PHONE_TYPE varchar(32) NOT NULL,
    E164_NUMBER varchar(32) NOT NULL,
    IS_VERIFIED boolean NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CONTACT_PHONE_PK ON CONTACT_PHONE (PHONE_ID, BUSINESS_DATE_FROM, IN_Z);

-- ContactEmail (BITEMPORAL)
CREATE TABLE CONTACT_EMAIL
(
    EMAIL_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    EMAIL_ADDRESS varchar(256) NOT NULL,
    IS_VERIFIED boolean NOT NULL,
    BOUNCE_COUNT int NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CONTACT_EMAIL_PK ON CONTACT_EMAIL (EMAIL_ID, BUSINESS_DATE_FROM, IN_Z);

-- Opportunity (BITEMPORAL)
CREATE TABLE OPPORTUNITY
(
    OPPORTUNITY_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    STAGE_CODE varchar(32) NOT NULL,
    AMOUNT decimal(18,2) NOT NULL,
    PROBABILITY int NOT NULL,
    EXPECTED_CLOSE_DATE datetime NOT NULL,
    OWNER_REP_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX OPPORTUNITY_PK ON OPPORTUNITY (OPPORTUNITY_ID, BUSINESS_DATE_FROM, IN_Z);

-- Quote (BITEMPORAL)
CREATE TABLE QUOTE
(
    QUOTE_ID bigint NOT NULL,
    OPPORTUNITY_ID bigint NOT NULL,
    QUOTE_NUMBER varchar(64) NOT NULL,
    STATUS varchar(32) NOT NULL,
    TOTAL_AMOUNT decimal(18,2) NOT NULL,
    VALID_UNTIL datetime NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX QUOTE_PK ON QUOTE (QUOTE_ID, BUSINESS_DATE_FROM, IN_Z);

-- QuoteLineItem (BITEMPORAL)
CREATE TABLE QUOTE_LINE_ITEM
(
    LINE_ID bigint NOT NULL,
    QUOTE_ID bigint NOT NULL,
    PRODUCT_ID bigint NOT NULL,
    QUANTITY int NOT NULL,
    UNIT_PRICE decimal(18,2) NOT NULL,
    DISCOUNT_PCT decimal(5,2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX QUOTE_LINE_ITEM_PK ON QUOTE_LINE_ITEM (LINE_ID, BUSINESS_DATE_FROM, IN_Z);

-- Contract (BITEMPORAL)
CREATE TABLE CONTRACT
(
    CONTRACT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    CONTRACT_NUMBER varchar(64) NOT NULL,
    STATUS varchar(32) NOT NULL,
    START_DATE datetime NOT NULL,
    END_DATE datetime NOT NULL,
    AUTO_RENEW boolean NOT NULL,
    TCV decimal(18,2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CONTRACT_PK ON CONTRACT (CONTRACT_ID, BUSINESS_DATE_FROM, IN_Z);

-- Subscription (BITEMPORAL)
CREATE TABLE SUBSCRIPTION
(
    SUBSCRIPTION_ID bigint NOT NULL,
    CONTRACT_ID bigint NOT NULL,
    PRODUCT_ID bigint NOT NULL,
    SEATS int NOT NULL,
    MRR decimal(18,2) NOT NULL,
    BILLING_CYCLE varchar(32) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX SUBSCRIPTION_PK ON SUBSCRIPTION (SUBSCRIPTION_ID, BUSINESS_DATE_FROM, IN_Z);

-- PriceBookEntry (BITEMPORAL)
CREATE TABLE PRICE_BOOK_ENTRY
(
    ENTRY_ID bigint NOT NULL,
    PRICE_BOOK_ID bigint NOT NULL,
    PRODUCT_ID bigint NOT NULL,
    UNIT_PRICE decimal(18,2) NOT NULL,
    CURRENCY varchar(3) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX PRICE_BOOK_ENTRY_PK ON PRICE_BOOK_ENTRY (ENTRY_ID, BUSINESS_DATE_FROM, IN_Z);

-- Call (AUDIT)
CREATE TABLE CALL_RECORD
(
    CALL_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    REP_ID bigint NOT NULL,
    DIRECTION varchar(16) NOT NULL,
    START_TIME datetime NOT NULL,
    DURATION_SECONDS int NOT NULL,
    OUTCOME_CODE varchar(32) NOT NULL,
    NOTES varchar(4000) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CALL_RECORD_PK ON CALL_RECORD (CALL_ID, IN_Z);

-- EmailMessage (AUDIT)
CREATE TABLE EMAIL_MESSAGE
(
    MESSAGE_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    REP_ID bigint NOT NULL,
    DIRECTION varchar(16) NOT NULL,
    SUBJECT varchar(256) NOT NULL,
    SENT_TIME datetime NOT NULL,
    OPENED_TIME datetime NULL,
    CLICKED_TIME datetime NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX EMAIL_MESSAGE_PK ON EMAIL_MESSAGE (MESSAGE_ID, IN_Z);

-- Meeting (AUDIT)
CREATE TABLE MEETING
(
    MEETING_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    REP_ID bigint NOT NULL,
    SUBJECT varchar(256) NOT NULL,
    START_TIME datetime NOT NULL,
    END_TIME datetime NOT NULL,
    LOCATION_TYPE varchar(32) NOT NULL,
    OUTCOME_CODE varchar(32) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX MEETING_PK ON MEETING (MEETING_ID, IN_Z);

-- TaskItem (AUDIT)
CREATE TABLE TASK_ITEM
(
    TASK_ID bigint NOT NULL,
    CUSTOMER_ID bigint NULL,
    REP_ID bigint NOT NULL,
    SUBJECT varchar(256) NOT NULL,
    DUE_DATE datetime NOT NULL,
    STATUS varchar(32) NOT NULL,
    PRIORITY varchar(16) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX TASK_ITEM_PK ON TASK_ITEM (TASK_ID, IN_Z);

-- Note (AUDIT)
CREATE TABLE NOTE_RECORD
(
    NOTE_ID bigint NOT NULL,
    ENTITY_TYPE varchar(64) NOT NULL,
    ENTITY_ID bigint NOT NULL,
    REP_ID bigint NOT NULL,
    BODY varchar(4000) NOT NULL,
    CREATED_TIME datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX NOTE_RECORD_PK ON NOTE_RECORD (NOTE_ID, IN_Z);

-- CaseComment (AUDIT)
CREATE TABLE CASE_COMMENT
(
    COMMENT_ID bigint NOT NULL,
    CASE_ID bigint NOT NULL,
    AUTHOR_REP_ID bigint NOT NULL,
    BODY varchar(4000) NOT NULL,
    CREATED_TIME datetime NOT NULL,
    IS_PUBLIC boolean NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CASE_COMMENT_PK ON CASE_COMMENT (COMMENT_ID, IN_Z);

-- Attachment (AUDIT)
CREATE TABLE ATTACHMENT
(
    ATTACHMENT_ID bigint NOT NULL,
    ENTITY_TYPE varchar(64) NOT NULL,
    ENTITY_ID bigint NOT NULL,
    FILE_NAME varchar(256) NOT NULL,
    MIME_TYPE varchar(128) NOT NULL,
    SIZE_BYTES bigint NOT NULL,
    STORAGE_REF varchar(256) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX ATTACHMENT_PK ON ATTACHMENT (ATTACHMENT_ID, IN_Z);

-- Campaign (BITEMPORAL)
CREATE TABLE CAMPAIGN
(
    CAMPAIGN_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    CAMPAIGN_TYPE varchar(32) NOT NULL,
    STATUS varchar(32) NOT NULL,
    BUDGET decimal(18,2) NOT NULL,
    START_DATE datetime NOT NULL,
    END_DATE datetime NOT NULL,
    OWNER_REP_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CAMPAIGN_PK ON CAMPAIGN (CAMPAIGN_ID, BUSINESS_DATE_FROM, IN_Z);

-- CampaignMember (BITEMPORAL)
CREATE TABLE CAMPAIGN_MEMBER
(
    MEMBER_ID bigint NOT NULL,
    CAMPAIGN_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    MEMBER_STATUS varchar(32) NOT NULL,
    RESPONDED_DATE datetime NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CAMPAIGN_MEMBER_PK ON CAMPAIGN_MEMBER (MEMBER_ID, BUSINESS_DATE_FROM, IN_Z);

-- OutreachSequence (BITEMPORAL)
CREATE TABLE OUTREACH_SEQUENCE
(
    SEQUENCE_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    IS_ACTIVE boolean NOT NULL,
    OWNER_REP_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX OUTREACH_SEQUENCE_PK ON OUTREACH_SEQUENCE (SEQUENCE_ID, BUSINESS_DATE_FROM, IN_Z);

-- OutreachStep (BITEMPORAL)
CREATE TABLE OUTREACH_STEP
(
    STEP_ID bigint NOT NULL,
    SEQUENCE_ID bigint NOT NULL,
    STEP_NUMBER int NOT NULL,
    CHANNEL varchar(32) NOT NULL,
    DELAY_DAYS int NOT NULL,
    TEMPLATE_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX OUTREACH_STEP_PK ON OUTREACH_STEP (STEP_ID, BUSINESS_DATE_FROM, IN_Z);

-- OutreachEnrollment (AUDIT)
CREATE TABLE OUTREACH_ENROLLMENT
(
    ENROLLMENT_ID bigint NOT NULL,
    SEQUENCE_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    ENROLLED_TIME datetime NOT NULL,
    CURRENT_STEP_NUMBER int NOT NULL,
    STATUS varchar(32) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX OUTREACH_ENROLLMENT_PK ON OUTREACH_ENROLLMENT (ENROLLMENT_ID, IN_Z);

-- MessageTemplate (BITEMPORAL)
CREATE TABLE MESSAGE_TEMPLATE
(
    TEMPLATE_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    CHANNEL varchar(32) NOT NULL,
    SUBJECT varchar(256) NOT NULL,
    BODY varchar(4000) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX MESSAGE_TEMPLATE_PK ON MESSAGE_TEMPLATE (TEMPLATE_ID, BUSINESS_DATE_FROM, IN_Z);

-- SupportCase (BITEMPORAL)
CREATE TABLE SUPPORT_CASE
(
    CASE_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    CONTACT_ID bigint NOT NULL,
    SUBJECT varchar(256) NOT NULL,
    STATUS varchar(32) NOT NULL,
    PRIORITY varchar(16) NOT NULL,
    OPENED_TIME datetime NOT NULL,
    CLOSED_TIME datetime NULL,
    ASSIGNED_REP_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX SUPPORT_CASE_PK ON SUPPORT_CASE (CASE_ID, BUSINESS_DATE_FROM, IN_Z);

-- CaseEscalation (AUDIT)
CREATE TABLE CASE_ESCALATION
(
    ESCALATION_ID bigint NOT NULL,
    CASE_ID bigint NOT NULL,
    ESCALATED_TO_REP_ID bigint NOT NULL,
    REASON varchar(256) NOT NULL,
    ESCALATED_TIME datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX CASE_ESCALATION_PK ON CASE_ESCALATION (ESCALATION_ID, IN_Z);

-- SlaPolicy (BITEMPORAL)
CREATE TABLE SLA_POLICY
(
    POLICY_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    PRIORITY varchar(16) NOT NULL,
    FIRST_RESPONSE_MINS int NOT NULL,
    RESOLUTION_MINS int NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX SLA_POLICY_PK ON SLA_POLICY (POLICY_ID, BUSINESS_DATE_FROM, IN_Z);

-- Invoice (BITEMPORAL)
CREATE TABLE INVOICE
(
    INVOICE_ID bigint NOT NULL,
    CUSTOMER_ID bigint NOT NULL,
    CONTRACT_ID bigint NOT NULL,
    INVOICE_NUMBER varchar(64) NOT NULL,
    ISSUE_DATE datetime NOT NULL,
    DUE_DATE datetime NOT NULL,
    TOTAL_AMOUNT decimal(18,2) NOT NULL,
    STATUS varchar(32) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX INVOICE_PK ON INVOICE (INVOICE_ID, BUSINESS_DATE_FROM, IN_Z);

-- InvoiceLine (BITEMPORAL)
CREATE TABLE INVOICE_LINE
(
    LINE_ID bigint NOT NULL,
    INVOICE_ID bigint NOT NULL,
    PRODUCT_ID bigint NOT NULL,
    DESCRIPTION varchar(256) NOT NULL,
    QUANTITY int NOT NULL,
    UNIT_PRICE decimal(18,2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX INVOICE_LINE_PK ON INVOICE_LINE (LINE_ID, BUSINESS_DATE_FROM, IN_Z);

-- Payment (AUDIT)
CREATE TABLE PAYMENT
(
    PAYMENT_ID bigint NOT NULL,
    INVOICE_ID bigint NOT NULL,
    AMOUNT decimal(18,2) NOT NULL,
    PAID_TIME datetime NOT NULL,
    METHOD varchar(32) NOT NULL,
    REFERENCE_CODE varchar(64) NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX PAYMENT_PK ON PAYMENT (PAYMENT_ID, IN_Z);

-- SalesRep (BITEMPORAL)
CREATE TABLE SALES_REP
(
    REP_ID bigint NOT NULL,
    FIRST_NAME varchar(64) NOT NULL,
    LAST_NAME varchar(64) NOT NULL,
    EMAIL varchar(256) NOT NULL,
    TEAM_ID bigint NOT NULL,
    MANAGER_REP_ID bigint NULL,
    HIRE_DATE datetime NOT NULL,
    TERMINATION_DATE datetime NULL,
    QUOTA_AMOUNT decimal(18,2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX SALES_REP_PK ON SALES_REP (REP_ID, BUSINESS_DATE_FROM, IN_Z);

-- Team (BITEMPORAL)
CREATE TABLE TEAM
(
    TEAM_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    REGION_CODE varchar(16) NOT NULL,
    MANAGER_REP_ID bigint NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX TEAM_PK ON TEAM (TEAM_ID, BUSINESS_DATE_FROM, IN_Z);

-- Territory (BITEMPORAL)
CREATE TABLE TERRITORY
(
    TERRITORY_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    REGION_CODE varchar(16) NOT NULL,
    COUNTRY_CODE varchar(2) NOT NULL,
    BUSINESS_DATE_FROM datetime NOT NULL,
    BUSINESS_DATE_THRU datetime NOT NULL,
    IN_Z datetime NOT NULL,
    OUT_Z datetime NOT NULL
);
CREATE UNIQUE INDEX TERRITORY_PK ON TERRITORY (TERRITORY_ID, BUSINESS_DATE_FROM, IN_Z);

-- Industry (PLAIN)
CREATE TABLE INDUSTRY
(
    INDUSTRY_CODE varchar(32) NOT NULL,
    NAME varchar(128) NOT NULL,
    SIC_CODE varchar(16) NOT NULL
);
CREATE UNIQUE INDEX INDUSTRY_PK ON INDUSTRY (INDUSTRY_CODE);

-- CustomerSegment (PLAIN)
CREATE TABLE CUSTOMER_SEGMENT
(
    SEGMENT_CODE varchar(32) NOT NULL,
    NAME varchar(128) NOT NULL,
    DESCRIPTION varchar(256) NOT NULL
);
CREATE UNIQUE INDEX CUSTOMER_SEGMENT_PK ON CUSTOMER_SEGMENT (SEGMENT_CODE);

-- PipelineStage (PLAIN)
CREATE TABLE PIPELINE_STAGE
(
    STAGE_CODE varchar(32) NOT NULL,
    NAME varchar(128) NOT NULL,
    SORT_ORDER int NOT NULL,
    IS_CLOSED boolean NOT NULL,
    IS_WON boolean NOT NULL
);
CREATE UNIQUE INDEX PIPELINE_STAGE_PK ON PIPELINE_STAGE (STAGE_CODE);

-- LeadSource (PLAIN)
CREATE TABLE LEAD_SOURCE
(
    SOURCE_CODE varchar(32) NOT NULL,
    NAME varchar(128) NOT NULL,
    CHANNEL varchar(32) NOT NULL
);
CREATE UNIQUE INDEX LEAD_SOURCE_PK ON LEAD_SOURCE (SOURCE_CODE);

-- Product (PLAIN)
CREATE TABLE PRODUCT
(
    PRODUCT_ID bigint NOT NULL,
    SKU varchar(64) NOT NULL,
    NAME varchar(128) NOT NULL,
    PRODUCT_FAMILY varchar(64) NOT NULL,
    IS_ACTIVE boolean NOT NULL
);
CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT (PRODUCT_ID);

-- PriceBook (PLAIN)
CREATE TABLE PRICE_BOOK
(
    PRICE_BOOK_ID bigint NOT NULL,
    NAME varchar(128) NOT NULL,
    CURRENCY varchar(3) NOT NULL,
    IS_STANDARD boolean NOT NULL
);
CREATE UNIQUE INDEX PRICE_BOOK_PK ON PRICE_BOOK (PRICE_BOOK_ID);

-- Tag (PLAIN)
CREATE TABLE TAG
(
    TAG_ID bigint NOT NULL,
    NAME varchar(64) NOT NULL,
    COLOR_HEX varchar(7) NOT NULL
);
CREATE UNIQUE INDEX TAG_PK ON TAG (TAG_ID);
