DROP TABLE IF EXISTS DIFF_BALANCE;
CREATE TABLE DIFF_BALANCE (
    BALANCE_ID INTEGER NOT NULL, QUANTITY DOUBLE NOT NULL, LABEL VARCHAR(64) NOT NULL, NOTE VARCHAR(32768),
    FROM_Z TIMESTAMP NOT NULL, THRU_Z TIMESTAMP NOT NULL,
    IN_Z TIMESTAMP NOT NULL, OUT_Z TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS DIFF_AUDIT;
CREATE TABLE DIFF_AUDIT (
    AUDIT_ID INTEGER NOT NULL, QUANTITY DOUBLE NOT NULL, LABEL VARCHAR(64) NOT NULL, NOTE VARCHAR(64),
    IN_Z TIMESTAMP NOT NULL, OUT_Z TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS DIFF_POSITION;
CREATE TABLE DIFF_POSITION (
    POSITION_ID INTEGER NOT NULL, QUANTITY DOUBLE NOT NULL, LABEL VARCHAR(64) NOT NULL, NOTE VARCHAR(64),
    FROM_Z TIMESTAMP NOT NULL, THRU_Z TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS DIFF_ENTRY;
CREATE TABLE DIFF_ENTRY (
    ENTRY_ID INTEGER NOT NULL, BALANCE_ID INTEGER NOT NULL, AMOUNT DOUBLE NOT NULL, LABEL VARCHAR(64) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL, THRU_Z TIMESTAMP NOT NULL,
    IN_Z TIMESTAMP NOT NULL, OUT_Z TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS DIFF_TAG;
CREATE TABLE DIFF_TAG (
    TAG_ID INTEGER NOT NULL, ENTRY_ID INTEGER NOT NULL, WEIGHT DOUBLE NOT NULL, LABEL VARCHAR(64) NOT NULL,
    FROM_Z TIMESTAMP NOT NULL, THRU_Z TIMESTAMP NOT NULL,
    IN_Z TIMESTAMP NOT NULL, OUT_Z TIMESTAMP NOT NULL);

DROP TABLE IF EXISTS DIFF_NUMERIC;
CREATE TABLE DIFF_NUMERIC (
    ID INTEGER NOT NULL, RATE REAL NOT NULL, QUANTITY DOUBLE NOT NULL, AMOUNT DECIMAL(18,4) NOT NULL);

DROP TABLE IF EXISTS DIFF_FINDER_VALUE;
CREATE TABLE DIFF_FINDER_VALUE (
    SCOPE_ID INTEGER NOT NULL,
    ROW_ID INTEGER NOT NULL,
    BUCKET_ID INTEGER NOT NULL,
    INT_VALUE INTEGER,
    LONG_VALUE BIGINT,
    DOUBLE_VALUE DOUBLE,
    FLOAT_VALUE REAL,
    DECIMAL_VALUE DECIMAL(30,4),
    TEXT_VALUE VARCHAR(128),
    BOOLEAN_VALUE BOOLEAN,
    TIMESTAMP_VALUE TIMESTAMP(3),
    BYTES_VALUE VARBINARY(65536),
    PRIMARY KEY (SCOPE_ID, ROW_ID));
